// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: zzcverwzrpfhcvnhvihb

class SupabaseConfig {
  static const String supabaseUrl = 'https://zzcverwzrpfhcvnhvihb.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Y3Zlcnd6cnBmaGN2bmh2aWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjQ2ODQsImV4cCI6MjA3Nzk0MDY4NH0.rTBAKOa0FRn074IGDalfe7WD9_yXNUVFrF08Z8SmkPo';
}
